package main;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import controller.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MainView extends javax.swing.JFrame {
    datacontroller dc;
    datakamarcontroller zz;
    public MainView() {
        initComponents();
        dc = new datacontroller(this);
        dc.isiTabel();
        zz = new datakamarcontroller(this);
        zz.isiTabelKamar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        temp = new javax.swing.JTextField();
        temp2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabelData = new javax.swing.JTable();
        jTextNama = new javax.swing.JTextField();
        jTextAlamat = new javax.swing.JTextField();
        jTextNomorTelepon = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jTextKamar = new javax.swing.JTextField();
        jTextJenisKelamin = new javax.swing.JTextField();
        jTextIdPasien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTabelKamar = new javax.swing.JTable();

        temp.setEditable(false);

        temp2.setEditable(false);
        temp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTabelData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTabelData);

        jTextAlamat.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlamatActionPerformed(evt);
            }
        });

        jTextNomorTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomorTeleponActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(153, 204, 255));
        btnsimpan.setForeground(new java.awt.Color(0, 51, 51));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setText("Update");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jTextKamar.setEditable(false);
        jTextKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKamarActionPerformed(evt);
            }
        });

        jTextJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextJenisKelaminActionPerformed(evt);
            }
        });

        jTextIdPasien.setEditable(false);

        jLabel1.setText("No. Telefon");

        jLabel2.setText("No Kamar");

        jLabel3.setText("Alamat");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("DATA PASIEN RUMAH SAKIT SUMANTO");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama");

        JTabelKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTabelKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabelKamarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTabelKamar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnhapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextNomorTelepon)
                                        .addComponent(jTextAlamat)
                                        .addComponent(jTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jTextKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(43, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextIdPasien)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKamarActionPerformed

    private void JTabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabelDataMouseClicked
        int kolom = JTabelData.getSelectedRow();
        jTextIdPasien.setText(JTabelData.getValueAt(kolom, 0).toString());
        jTextNama.setText(JTabelData.getValueAt(kolom, 1).toString());
        jTextAlamat.setText(JTabelData.getValueAt(kolom, 2).toString());
        jTextNomorTelepon.setText(JTabelData.getValueAt(kolom, 4).toString());
        jTextKamar.setText(JTabelData.getValueAt(kolom, 5).toString());
        jTextJenisKelamin.setText(JTabelData.getValueAt(kolom, 3).toString());
    }//GEN-LAST:event_JTabelDataMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        jTextIdPasien.setText("");
        jTextNama.setText("");
        jTextAlamat.setText("");
        jTextNomorTelepon.setText("");
        jTextKamar.setText(""); 
        jTextJenisKelamin.setText("");
        JTabelData.clearSelection(); 
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

        if (getjTextKamar().getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih Kamar terlebih dahulu dengan mengeklik salah satu kamar di dalam tabel", "Input Tidak Lengkap", JOptionPane.ERROR_MESSAGE);
        }else {
            int kolom = JTabelKamar.getSelectedRow();
            if(Integer.parseInt(JTabelKamar.getValueAt(kolom, 7).toString()) > Integer.parseInt(JTabelKamar.getValueAt(kolom, 8).toString())){
                JOptionPane.showMessageDialog(this, "Kapasitas Kamar sudah penuh, Silahkan pilih kamar lain", "Kamar Penuh", JOptionPane.ERROR_MESSAGE);
            } else {
                dc.insert();
                dc.isiTabel();
                zz.updateKamar();
                zz.isiTabelKamar();
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void jTextAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlamatActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        int kolom = JTabelKamar.getSelectedRow();
        if(Integer.parseInt(JTabelKamar.getValueAt(kolom, 7).toString()) > Integer.parseInt(JTabelKamar.getValueAt(kolom, 8).toString())){
            JOptionPane.showMessageDialog(this, "Kapasitas Kamar sudah penuh, Silahkan pilih kamar lain", "Kamar Penuh", JOptionPane.ERROR_MESSAGE);
        } else if (getjTextIdPasien().getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih Dahulu data yang mau diubah dengan klik salah satu data di tabel", "Input Tidak Lengkap", JOptionPane.ERROR_MESSAGE);
        } else {
            dc.update();
            dc.isiTabel();
            zz.updateKamar();
            zz.isiTabelKamar();
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        if (getTemp().getText().isEmpty() && getTemp2().getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih Dahulu data yang mau dihapus dengan klik salah satu data di tabel", "Data Tidak Lengkap", JOptionPane.ERROR_MESSAGE);
        } else {
            dc.delete();
            dc.isiTabel(); 
            zz.deletekamar();
            zz.isiTabelKamar();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jTextNomorTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomorTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomorTeleponActionPerformed

    private void jTextJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextJenisKelaminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PilihView v = new PilihView();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTabelKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabelKamarMouseClicked
        int kolom = JTabelKamar.getSelectedRow();
        jTextKamar.setText(JTabelKamar.getValueAt(kolom, 1).toString());
        temp.setText(JTabelKamar.getValueAt(kolom, 7).toString());
        temp2.setText(JTabelKamar.getValueAt(kolom, 8).toString());
    }//GEN-LAST:event_JTabelKamarMouseClicked

    private void temp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp2ActionPerformed
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTabelData;
    private javax.swing.JTable JTabelKamar;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextAlamat;
    private javax.swing.JTextField jTextIdPasien;
    private javax.swing.JTextField jTextJenisKelamin;
    private javax.swing.JTextField jTextKamar;
    private javax.swing.JTextField jTextNama;
    private javax.swing.JTextField jTextNomorTelepon;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField temp2;
    // End of variables declaration//GEN-END:variables

    public datacontroller getDc() {
        return dc;
    }


    public void setDc(datacontroller dc) {
        this.dc = dc;
    }

    public JButton getBtnclear() {
        return btnclear;
    }

    public void setBtnclear(JButton btnclear) {
        this.btnclear = btnclear;
    }

    public JButton getBtnedit() {
        return btnedit;
    }

    public void setBtnedit(JButton btnedit) {
        this.btnedit = btnedit;
    }

    public JButton getBtnhapus() {
        return btnhapus;
    }

    public void setBtnhapus(JButton btnhapus) {
        this.btnhapus = btnhapus;
    }

    public JButton getBtnsimpan() {
        return btnsimpan;
    }

    public void setBtnsimpan(JButton btnsimpan) {
        this.btnsimpan = btnsimpan;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getjTextAlamat() {
        return jTextAlamat;
    }

    public void setjTextAlamat(JTextField jTextAlamat) {
        this.jTextAlamat = jTextAlamat;
    }

    public JTextField getjTextIdPasien() {
        return jTextIdPasien;
    }

    public void setjTextIdPasien(JTextField jTextIdPasien) {
        this.jTextIdPasien = jTextIdPasien;
    }

    public JTextField getjTextJenisKelamin() {
        return jTextJenisKelamin;
    }

    public void setjTextJenisKelamin(JTextField jTextJenisKelamin) {
        this.jTextJenisKelamin = jTextJenisKelamin;
    }

    public JTextField getjTextKamar() {
        return jTextKamar;
    }

    public void setjTextKamar(JTextField jTextKamar) {
        this.jTextKamar = jTextKamar;
    }

    public JTextField getjTextNama() {
        return jTextNama;
    }

    public void setjTextNama(JTextField jTextNama) {
        this.jTextNama = jTextNama;
    }

    public JTextField getjTextNomorTelepon() {
        return jTextNomorTelepon;
    }

    public void setjTextNomorTelepon(JTextField jTextNomorTelepon) {
        this.jTextNomorTelepon = jTextNomorTelepon;
    }
    
    public JTable getJTabelData() {
        return JTabelData;
    }

    public void setJTabelData(JTable JTabelData) {
        this.JTabelData = JTabelData;
    }

    public JTable getJTabelKamar() {
        return JTabelKamar;
    }

    public void setJTabelKamar(JTable JTabelKamar) {
        this.JTabelKamar = JTabelKamar;
    }

    public datakamarcontroller getZz() {
        return zz;
    }

    public void setZz(datakamarcontroller zz) {
        this.zz = zz;
    }

    public JTextField getTemp() {
        return temp;
    }

    public void setTemp(JTextField temp) {
        this.temp = temp;
    }

    public JTextField getTemp2() {
        return temp2;
    }

    public void setTemp2(JTextField temp2) {
        this.temp2 = temp2;
    }
     
    
}
